apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
  labels:
    app: code-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
      - name: code-server
        image: codercom/code-server:latest
        imagePullPolicy: Always
        args:
        - --auth=password
        - --disable-telemetry
        - --bind-addr=0.0.0.0:8080
        env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: code-server-secret
              key: password
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
        volumeMounts:
        - name: code-server-data
          mountPath: /home/coder
      volumes:
      - name: code-server-data
        persistentVolumeClaim:
          claimName: code-server-pvc